var { GroundType } = require('./ground')
// 一张卡牌的定义，剩下的到时候再补充
// {
//     id: 0, //卡牌ID
//     name: "xxxxxx", //卡牌名字
//     cardType: CardType.CHARACTER, //卡牌类型-生物/咒语(针对生物)/法术(针对英雄)
//     cost: 3, //卡牌花费
//     terrain: [], //地形需求
//     content: `xxxxxxxxxx`, //卡牌描述
//     attack: 2, //卡牌攻击力
//     life: 1, //卡牌血量
//     action: 1, //行动力
//     actionBase: 1, //基础行动力
//     attackBase: 2, //卡牌基础攻击力
//     lifeBase: 1, //卡牌基础血量
//     type: [""], //卡牌种族-生物/咒语(特定生物种族生效)
//     isTaunt: true, //是否挑衅
//     isEvolution: true, //是否进化
//     attackEvolution: 10, //进化后攻击力
//     lifeEvolution: 10, //进化后血量
//     actionEvolution: 2, //进化后行动力
//     contentEvolution: //进化后描述
//     isAttack: 1, //是否攻击，0-未攻击，1-已攻击
//     isMove: 1, //是否移动，0-未移动，1-已移动
//     isLaunch: 0, //是否发动效果，0-未发动，1-已发动
//     status: 0, //当前状态，0-正常，1-恐惧，2-止步，3-混乱，4-重伤
//     statusRound: 0, //状态持续回合
//     effect: 0, //卡牌效果，0-无，1-战吼，2-亡语，3-回合，4-光环，5-永续

//     卡牌生命周期
//     onHand: function() {}, //在手牌时
//     onStart: function() {}, //打出时
//     onOtherCardStart: function() {}, //别的卡牌打出时
//     onMyTurnStart: function() {}, //我的回合开始时
//     onMyTurnEnd: function() {}, //我的回合结束时
//     onOtherTurnStart: function() {}, //对方的回合开始时
//     onOtherTurnEnd: function() {}, //对方的回合结束时
//     onChooseTarget: function() {}, //选定效果目标时
//     onBeChoosedTarget: function() {}, //被选定效果目标时
//     onAttackStart: function() {}, //攻击前
//     onAttackEnd: function() {}, //攻击后
//     onBeAttackedStart: function() {}, //被攻击前
//     onBeAttackedEnd: function() {}, //被攻击后
//     onEnd: function() {}, //死亡时
//     onTableCardChange: function() {}, //桌面卡牌变动时
//     onCemetery: function() {}, //在墓地时
//     onExtradimensional: function() {}, //在异次元时
// }
//卡牌类型
const CardType = {
    MANTRA: 1,
    CHARACTER: 2,
    SPELL: 3,
    HERO: 4
}

//卡牌状态
const CardStatus = {
    NORMAL: 0,
    TERROR: 1,
    STOP: 2,
    CONFUSION: 3,
    WOUND: 4
}

//卡牌状态
const CardEffect = {
    KONG: 0,
    WARCRY: 1,
    DEADWORDS: 2,
    ROUND: 3,
    HALO: 4,
    ETERNAL: 5
}

//卡牌
const CardList = [
    {
        id: 1,
        name: "壹",
        cardType: CardType.CHARACTER,
        cost: 2,
        terrain: [GroundType.EARTH],
        content: `这是第1张牌`,
        attack: 1,
        life: 2,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 2,
        type: [""],
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
        onStart: function() {
            
        },
    },
    {
        id: 2,
        name: "贰",
        cardType: CardType.CHARACTER,
        cost: 7,
        terrain: [GroundType.EARTH, GroundType.EARTH, GroundType.VOLCANO],
        content: `这是第2张牌`,
        attack: 7,
        life: 7,
        action: 1,
        actionBase: 1,
        attackBase: 7,
        lifeBase: 7,
        type: [""],
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 3,
        name: "叁",
        cardType: CardType.CHARACTER,
        cost: 1,
        terrain: [GroundType.NONE],
        content: `这是第3张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 4,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        terrain: [GroundType.OCEAN, GroundType.EARTH, GroundType.VOLCANO, GroundType.FURUKI],
        content: `这是第4张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },  
    {
        id: 5,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第5张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 6,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第6张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 7,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第7张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 8,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第8张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 9,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第9张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 10,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第10张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 11,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第11张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 12,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第12张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 13,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第13张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 14,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第14张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 15,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第15张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 16,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第16张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 17,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第17张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 18,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第18张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 19,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第19张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 20,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第20张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 21,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第21张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 22,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第22张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 23,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第23张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 24,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第24张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    },
    {
        id: 25,
        name: "肆",
        cardType: CardType.CHARACTER,
        cost: 1,
        content: `这是第25张牌`,
        attack: 1,
        life: 1,
        action: 1,
        actionBase: 1,
        attackBase: 1,
        lifeBase: 1,
        type: [""],
        isTaunt: true,
        isAttack: 1,
        isMove: 1,
        isLaunch: 0,
        status: CardStatus.NORMAL,
        effect: CardEffect.KONG,
        statusRound: 0,
    }
]
module.exports = {
    CardType,
    CardStatus,
    CardEffect,
    Cards: CardList
}